### ISSUE TITLE
Unsafety: implementing an unsafe trait is an unsafe operation

### ISSUE THREAD

**Issue by ojeda** [ferrocene/specification#160]
The list of unsafe operations at 19:3 is missing implementing an unsafe trait.

**Comment by steveklabnik** [comment]
Does this mean that like, according to the spec, `unsafe impl` is effectively just its own syntax, distinct from `impl`? I guess this is what B.556:1 means?

**Comment by Veykril** [comment]
It's not its own syntax per se, we just give trait impls with an `unsafe` keyword a separate name with that glossary entry so that we can refer to that more easily.

As a side note, https://spec.ferrocene.dev/implementations.html#implementations 11:10 lists `A trait implementation shall be an unsafe trait implementation if and only if it implements an unsafe trait.`
